### ISSUE TITLE
Crashing with the trade/quest update

### ISSUE THREAD

**Issue by pixzi** [FlashHUN/FlashNPCs#1]
Hello there,

I recently updated to the latest version, doing so caused my pack to crash when creating or loading a world. I rolled back to the previous version and it works fine.  I disabled the mod and tested without - works perfectly fine. 

No optifine or sodium installed that might cause an issue and im not seeing an issue on anything else.  Any help would be grateful.

Crash log provided: https://pastebin.com/7y9fDX4W

**Comment by FlashHUN** [comment]
The issue is with the way Untamed Wilds' entities work, for some odd reason they can't be instantiated from their EntityType.
