### ISSUE TITLE
I can't teleport to a location

### ISSUE THREAD

**Issue by tatertotto** [FlashHUN/FlashNPCs#19]
I've tried creating new functions but for some reason I can't make myself tp from one place to another place.

**Comment by FlashHUN** [comment]
Could you send your function file in here? Should be in '_world folder_/flashnpcs/functions/'

**Comment by tatertotto** [comment]
[Teleport (1).txt](https://github.com/FlashHUN/FlashNPCs/files/8137830/Teleport.1.txt)

**Comment by tatertotto** [comment]
idk how to code but i just really want to get myself to tp

**Comment by FlashHUN** [comment]
```
-296,69,24
/tp @p -296 ~ 69 ~ 24
```

A couple things:
- First line should be your list of parameters. Parameters are things that if part of the commands you put into the function, they'll be replaced with the matching parameter you have to give when setting them up in the dialogue. Think about it this way: You can have very specific functions that do very specific things and very generic functions that can be adapted to how you want to use them in each part of the dialogue.

For example, a specific function would be:
```

/tp @p -296 69 24
/give @p minecraft:apple 1
/tellraw @p {"text":"Here you go, have an apple!","color":"yellow"}
```

While generic functions look more like this:
```
x,y,z
/tp @p x y z
```

```
item,amount
/give @p item amount
```

```
pText,pColor
/tellraw @p {"text":"pText","color":"pColor"}
```

You can also mix these two types of functions together if you'd like. Once you have your functions, you can call them from dialogues like it's shown in the function list. For example, if it's shown just as _tpToNarnia_, then it has no parameters and you can simply call it. If it's shown as _teleport::x,y,z_, then it has 3 parameters, in this case the x, y and z coordinates you want to teleport to, and you have to give those parameters each time you want to use it in the dialogue by typing them into the text box just above the save button. In this case I'm guessing you'd want to type _-296,69,24_, and then it'll be saved to the dialogue node as _teleport::-296,69,24_.

- Look at your /tp command. Does that look right to you?

You want to teleport the player to a 5 dimensional space, which doesn't really exist in Minecraft, and you should only use '~' if you want to do something ___relative___ to the player's coordinates.

_/tp @p -296 ~69 ~24_ would tp them to x: -296, y: playerY+69, z: playerZ+24.
_/tp @p -296 69 24_ would tp them to x: -296, y: 69, z: 24.
_/tp @p -296 ~ ~_ would tp them to x: -296, y: playerY, z: playerZ.

Please learn how Minecraft commands work :)

**Comment by tatertotto** [comment]
Thanks bro! I love this mod btw.
