### ISSUE TITLE
Incompatible with the "Untamed Wilds" Mod

### ISSUE THREAD

**Issue by Jrassic** [FlashHUN/FlashNPCs#2]
Since updating to version 1.1 of your mod it crashes on world creation, the issue persists in version 1.1.1.

I'm using Forge 36.2.2 and Untamed Wilds 1.3.1 (newest)

I've attached my latest crash log with only your mod, untamed wilds and citadel (library mod) running.

No clue how and why the two mods would conflict with eachother.

[crash-2021-08-29_20.27.44-server.txt](https://github.com/FlashHUN/FlashNPCs/files/7073019/crash-2021-08-29_20.27.44-server.txt)

**Comment by FlashHUN** [comment]
This is a known issue, however I can't really do anything to fix it. For some reason, Untamed Wilds' mobs cannot be instantiated from their registered EntityType (according to the crash log it's something with their attributes, though I don't know why that would affect instantiating them).

**Comment by Jrassic** [comment]
Ah I see, I might open an issue on their end then. 
Maybe it'll be fixed in the future since their mod is still in development as well.
Thanks anyway!

**Comment by FlashHUN** [comment]
It will be fixed in Untamed Wilds' next update ^^

**Comment by Jrassic** [comment]
That's great! Thank you for letting me know! Can't wait to play around with your mod :)
