### ISSUE TITLE
Can't join to my Mohist server

### ISSUE THREAD

**Issue by 77Delta** [FlashHUN/FlashNPCs#28]
When I try to join to my server i get stuck on the "Joining World" screen. I have like 92 mods loaded and i don't know why this happens

Forge version: 1.16.5-36.2.35

Mohist version: 1.16.5-1055

Flash's NPCs version: 1.16.5-1.1.4

**Comment by FlashHUN** [comment]
Alright, lemme just randomly pick out 91 other mods out of 14727 on curseforge and see if the same happens. Seriously, what did you expect?

Provide client and server logs, and your list of mods.
