### ISSUE TITLE
Bug with Functions

### ISSUE THREAD

**Issue by Naimche** [FlashHUN/FlashNPCs#34]
I have created a server and I have put npc, everything works correctly except when I put a function that teleports, it is also well written because it does the teleportation but it only works for one person, the others, even if we start the function, it does not work. I try in survival and dont work for me too, idk i reinstall minecraft too and the problem persist.

**Comment by FlashHUN** [comment]
Send your function file here. You can find it in your _world folder_/flashnpcs/functions

**Comment by Naimche** [comment]
I was trying to find the error and when i use in Intellij some users names, function tp dont works, try using the name EmptySl.
function file
```
x,y,z
/tp @p x y z
```
[teleport.txt](https://github.com/FlashHUN/FlashNPCs/files/9429099/teleport.txt)

i cant send because dont sopport it i change extension to txt

**Comment by Naimche** [comment]
I found the error, when u replace FunctionUtil.replaceParameters(command, paramNames[i], param); if the parameter has a letter of the name it also replaces it with the coordinate.

**Comment by FlashHUN** [comment]
Good shout! Reordered the replacement so the parameters get replaced before the selectors, meaning player names (or parts of them) shouldn't be replaced by parameters. In any case, it's good practice use more descriptive/unique parameter names
