### ISSUE TITLE
when entering a server it stays on the loading screen entering the world

### ISSUE THREAD

**Issue by Insectoidemalebolo** [FlashHUN/FlashNPCs#36]
I have a server on the exaroton host, and when I installed the flash npc mod, me and the other players, when trying to enter, stayed on the entering the world screen, when I finally kicked them out, I managed to solve it by entering a singular world before entering the server, but I would like a concrete solution so I don't have to do it, we have 86 mods on the server

[1.18.2]+SecurityCraft+v1.9.3.1.jar

[1.18.x]-Epic-Knights-Armor-and-Weapons-6.3v.jar

additional_lights-1.18.2-2.1.4.jar

AdvancementPlaques-1.18.2-1.4.5.1.jar

alexsmobs-1.18.6.jar

AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar

Amplified_Nether_v1.1.1.jar

appleskin-forge-mc1.18-2.4.0.jar

Aquaculture-1.18.2-2.3.8.jar

architectury-4.9.83-forge.jar

artifacts-1.18.2-4.1.0.jar

badpackets-forge-0.1.2.jar

betteranimalsplus-1.18.2-11.0.5-forge.jar

BiomesOPlenty-1.18.2-16.0.0.134.jar

bonsaitrees3-3.1.0.jar

bygonenether-1.2.1-1.18.2.jar

camera-1.18.2-1.0.4.jar

carryon-1.18.2-1.17.0.8.jar

cfm-7.0.0-pre29-1.18.2.jar

chipped-1.18.2-1.2.1-forge.jar

citadel-1.11.3-1.18.2.jar

comforts-forge-1.18.2-5.0.0.4.jar

CreativeCore_FORGE_v2.6.15_mc1.18.2.jar

creeperoverhaul-1.18.2-1.3.0-forge.jar

Croptopia-1.18.2-FORGE-2.1.0.jar

curios-forge-1.18.2-5.0.7.0.jar

duckling-1.0.6-forge.jar

DungeonCrawl-1.18.2-2.3.9.jar

DungeonsArise-1.18.2-2.1.50d-beta.jar

DynamicTrees-1.18.2-0.11.0-Alpha2.jar

EarthMobs-1.18.2-1.1.2.jar

elevatorid-1.18.2-1.8.4.jar

emotecraft-for-MC1.18.2-2.2.4-forge.jar

expandability-6.0.0.jar

extragolems-18.2.3.jar

EyesInTheDarkness-1.18.2-1.2.7.jar

flashnpcs-1.18.1-1.1.4v2.jar

FramedBlocks-5.6.0.jar

fromtheshadows-1.81.jar

geckolib-forge-1.18-3.0.36.jar

goblintraders-1.7.2-1.18.2.jar

hexerei-0.2.2.jar

Iceberg-1.18.2-1.0.44.jar

Incendium_v5.0.4.jar

infernal-expansion-1.18.2-2.5.0.jar

InventoryProfilesNext-forge-1.18.2-1.7.0.jar

jei-1.18.2-9.7.1.255.jar

journeymap-1.18.2-5.8.5-forge.jar

kotlinforforge-3.6.0-obf.jar

libnonymous-2.1.0.jar

mcw-bridges-2.0.3-mc1.18.2.jar

mcw-doors-1.0.7-mc1.18.2.jar

mcw-windows-2.0.3-mc1.18.2.jar

minecraft-comes-alive-7.3.20+1.18.2-universal.jar

modernlife-1.18.2-1.54.jar

Monke+Madness+1.13.2.jar

MoreVanillaArmor-1.18.2-3.1.1.jar

occultism-1.18.2-1.33.3.jar

OfflineSkins-1.18.2-v2.jar

Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.3.jar

okzoomer-1.18.2-1.1.0.jar

Orcz_0.76_1.18.2.jar

Paraglider-1.18.2-1.6.0.0.jar

Patchouli-1.18.2-71.1.jar

player-animation-lib-forge-0.2.0.jar

PlayerRevive_FORGE_v2.0.9_mc1.18.2.jar

polymorph-forge-1.18.2-0.44.jar

reap-1.18.2-1.0.0.jar

scuba_gear-1.18.2-1.0.4.jar

selene-1.18.2-1.17.9.jar

sophisticatedbackpacks-1.18.2-3.18.17.680.jar

sophisticatedcore-1.18.2-0.5.1.98.jar

supplementaries-1.18.2-1.4.8.jar

TerraBlender-forge-1.18.2-1.1.0.102.jar

The_Undergarden-1.18.2-0.7.1.jar

tombstone-7.5.0-1.18.2.jar

Trapcraft-1.18.2-3.6.7.jar

untamedwilds-1.18.2-2.2.0.jar

voicechat-forge-1.18.2-2.3.8.jar

WeaponThrow-1.18.2-5.7.jar

whisperwoods-1.18.2-2.1.0-forge.jar

wthit-forge-4.13.1.jar

YungsApi-1.18.2-Forge-2.0.8.jar

YungsBetterDungeons-1.18.2-Forge-2.1.0.jar

YungsBetterMineshafts-1.18.2-Forge-2.2.jar

YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar

**Comment by FlashHUN** [comment]
Alex's Mobs and Hexerei are known to cause this, should be fixed in the next version

**Comment by Insectoidemalebolo** [comment]
cuando tiene disponible la nueva version para la 1.18.2?

**Comment by FlashHUN** [comment]
lo más probable es que antes de fin de año

**Comment by teinac2012** [comment]
The exact same thing happens to me, and I have removed the alex mobs and nothing, it keeps happening, I hope that in the next update you can add it
