### ISSUE TITLE
flashnpcs bug

### ISSUE THREAD

**Issue by digipra** [FlashHUN/FlashNPCs#46]
[server] I have flashnpcs-1.18.1-1.1.4v2 and I'm on a server, and when I create an npc and put a teleport function on it or give it an object it doesn't give it to me or it doesn't do the function, someone knows how to solve it ?

**Comment by FlashHUN** [comment]
Could you provide more info please? Anything in your server logs that seems off, does the same thing work in singleplayer but not on your server, do you have any other mods installed, etc.?

**Comment by digipra** [comment]
I have the same mods that I use in single player mode as on the server and I have plugins on the server that would be: world edit, deluxejoin, one for discord, easywhitelist, lighting_sword, playertime, simplejail;

and the mods I have are: [1.18.2]+SecurityCraft+v1.9.3.1.jar
AI-Enhancements-1.18.2-0.5.2.jar
alexsmobs-1.18.6.jar
Aquaculture-1.18.2-2.3.8.jar
BiomesOPlenty-1.18.2-16.0.0.134.jar
camera-1.18.2-1.0.5.jar
Chunk+Pregenerator-1.18-4.1.0.jar
citadel-1.11.3-1.18.2.jar
Groups-forge-1.18.2-8.0.0+15.jar
corpse-1.18.2-1.0.1.jar
CosmeticArmorReworked-1.18.2-v2a.jar
CraftTweaker-forge-1.18.2-9.1.196.jar
creeperoverhaul-1.18.2-1.3.0-forge.jar
Display+Case-forge-1.18.2-1.0.2.jar
DungeonCrawl-1.18.2-2.3.10.jar
Enhanced_Celestials-forge-1.18.2-2.0.7 (1).jar
FarmersDelight-1.18.2-1.2.0.jar
ferritecore-4.2.1-forge.jar
flashnpcs-1.18.1-1.1.4v2.jar
geckolib-forge-1.18-3.0.45.jar
hexerei-0.1.19.jar
lazydfu-0.1.2.jar
memory leak fix-1.18.2-0.7.0.jar
scuba gear-1.18.2-1.0.4.jar
SimpleStorageNetwork-1.18.2-1.6.2 (1).jar
fancy backpacks-1.18.2-3.18.24.704.jar
sophisticatedcore-1.18.2-0.5.13.132.jar
starlight-1.0.2+forge.546ae87.jar
TerraBlender-forge-1.18.2-1.2.0.126.jar
The_Wild_Update_Mod_V1.3_Minecraft_1.18.jar
Torchmaster-18.1.0.jar
TreeChop-1.18.2-forge-0.16.3.jar
vanillamor+.jar
voice chat-forge-1.18.2-2.2.32.jar
worldguard-bukkit-7.0.7-dist.jar
YungsApi-1.18.2-Forge-2.0.8.jar
YungsBetterDungeons-1.18.2-Forge-2.1.0.jar
YungsBetterMineshafts-1.18.2-Forge-2.2.jar;

within the served in the configuration sections I have not touched anything.

**Comment by digipra** [comment]
and the server is magma

**Comment by JustRed23** [comment]
Should be fixed in the newest build of Magma (1a50ede7)

**Comment by FlashHUN** [comment]
Gosh I need to get better at managing issues...

> Should be fixed in the newest build of Magma (1a50ede7)

Thank you @JustRed23 !
