### ISSUE TITLE
UTF character support

### ISSUE THREAD

**Issue by airoons** [FlashHUN/FlashNPCs#5]
Hello,

Thank you for creating this mod, finally a NPC mod for 1.16 👍 

I have found an issue with UTF characters. I expected the dialogue menu to support UTF characters as Minecraft chat can, but it replaces some UTF characters with question marks (?). 

You can test this by setting name of a NPC to "aāsšuū" - this will work.
But when using the same characters in the dialogue, after saving and reopening I see "a?sšu?".

Could you please fix this?

**Comment by FlashHUN** [comment]
Will be fixed in the next update
