### ISSUE TITLE
Does Flash's NPCs crash with ALL modded items as quest rewards? Bug/Question/Compat Error?

### ISSUE THREAD

**Issue by APrimevalWorld** [FlashHUN/FlashNPCs#54]
Hey there, today I've spent giving MC with **Flash's NPCs** a proper test spin. I've been working out how to do quests, and had this one in mind as the starting quest where the player speaks with the NPC to get a gun. **(MrCrayfish's Guns/Additional Guns)**. I customised the gun as per plan, and went into the take **from inventory** segment, and as a test tried to put a stock from the MCG addon Additional Guns, only for the entire game to **freeze for longer than a couple of minutes.** As a result, I shut it, and was left with the most important question; **is that supposed to happen?** And I'm just asking because nobody else seems to have reported an issue with **3d items** causing the game to freeze here. This is the only item I've tried, and of course it's not vanilla game so that might explain it. I thought it'd be useful for you to know though.

I would join the discord server, but I am not allowed to at this moment, under any circumstances. I simply wondered if this was a simple compatibility error, or not. 

**Note: I've highlighted key words in bold and there was no crash log as it froze instead.**

![Minecraft_ 1 18 2 - Singleplayer 25_12_2022 18_08_31](https://user-images.githubusercontent.com/84665486/209478474-cf5cdbb2-8450-439d-bacd-d0eb257c11ec.png)

**Update: Second attempt, gave me an error this time; -805306369. Strangely gave no crash log.**

**Comment by FlashHUN** [comment]
Modded items should definitely work with quests. Is there anything strange in your logs when you tried this?

**Comment by APrimevalWorld** [comment]
> Modded items should definitely work with quests. Is there anything strange in your logs when you tried this?

Sorry, would you mind clarifying this? I did not get any crash log other than one, and that related to a different mod. However, I did notice there were two tabs called the exact same thing; one in the main quest editor GUI, and another in the objective designer GUI. The one in the objective designer works, but the one in the main GUI doesn't. It doesn't even let me select the gun attachment or gun in that GUI. Next time around I'll throw in the minecraft output log if that's what you're referring to, and see what happens.

**Comment by APrimevalWorld** [comment]
Update: Just came online onto MC this morning, and there's been a bit of a development. It's fixed itself now, but I think I might've worked out the root cause. In the comment before, I mentioned another mod caused a crash. What I think happened is possibly that mod is incompatible with one of the other mods, but I'm not sure as I can't remember if the problem continued afterwards; my mind is telling me it did.
