### ISSUE TITLE
[Question] How to edit functions?

### ISSUE THREAD

**Issue by Catomax262** [FlashHUN/FlashNPCs#55]

**Comment by FlashHUN** [comment]
You can only do it through the files atm. Go to `*world_name*\flashnpcs\functions` and you can see all your custom functions.
First line is the parameters the function has (if it has no parameters, then the first line will be empty)
The rest are the commands and functions that'll run in the order they're shown. Each command and function should be on a new line. Example: 
```
xPos,yPos,zPos,theBlock
/setblock xPos yPos zPos theBlock
```
