### ISSUE TITLE
Migrate quest/dialogue/function data into datapack

### ISSUE THREAD

**Issue by TqLxQuanZ** [FlashHUN/FlashNPCs#63]
Currently, all the data are stored inside the world/flashnpcs folder, the reason why I am suggesting this is that there isn't any way to copy a "preset" quest data into a newly generated world, not that I know of for 1.18 mods, it can only be done manually.

Kubejs/Global Datapack provides easy access to pre-configured data pack for mod pack developers to access. So if the quest data are being saved/produced in the data pack, it can be easily set up for mod pack developers to initiate the quest without having a preset map.

E.G
1. Some random player creates a new world
2. flashnpcs data pack already exist in the data pack from certain mods to override
3. Quest is instantly accessible without any manual setup and can be used by the player immediately

**Comment by FlashHUN** [comment]
Using datapacks would require me to do a complete rewrite of how I handle npc data. I plan on doing that one day, but for now I'd rather stick to what I have. I am however working on a way to make globally accessible files for the mod. Coming next update ^^

**Comment by TqLxQuanZ** [comment]
That sounds great! It doesn't need to work as a datapack! As long as it is accessible outside of world folder then everything is fine since we can pre-place the folder inside the modpack and it can be read instantly!
Any idea when it will be released or any estimate time?

**Comment by TqLxQuanZ** [comment]
Closing this as the newest version has the global access.
