### ISSUE TITLE
Crash when equipping item from BetterAnimals+ to NPC

### ISSUE THREAD

**Issue by GamerGaven** [FlashHUN/FlashNPCs#8]
Link to Crash Report: https://paste.ee/p/YZc3U
I equipped a wolf cape from the BetterAnimals+ mod and it works properly unless curious is installed.
I assume this happens because the cape can be equipped in a curios slot as well as the normal body slot.

**Comment by FlashHUN** [comment]
The crash happens because BetterAnimals+ assumes the NPC is a player. I recommend making an issue on their end about why they should always check before casting.
